import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

import { getServerSession } from "next-auth";
import SessionProvider from '@/utils/SeassionProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Book-Flow",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Navbar></Navbar>
          {children}
        </SessionProvider>

      </body>
    </html>
  );
}
